version: '3.8'

services:
  app:
    build: .
    network_mode: host
    volumes:
      - ./downloads:/app/downloads
      - ./cookies.txt:/app/cookies.txt
    environment:
      - FLASK_ENV=production
      - PROXY_URL=socks5://127.0.0.1:40000
    restart: always
